import pyautogui as p
import time
import keyboard as k
a = int(input('Выберите программ, которую хотите запустить: 1)Yandex; 2)Google Chrome; 3)Microsoft Edge'))
f = open('123.txt', 'r', encoding="utf-8")
str1 = f.readline().strip()
str2 = f.readline().strip()
str3 = f.readline().strip()
p.press('win')
time.sleep(0.5)
p.write('123.txt')
time.sleep(0.5)
p.press('enter')
time.sleep(0.5)
if a == 1:
    p.moveTo(264, 239)
    time.sleep(0.5)
    p.doubleClick()
    time.sleep(0.5)
    p.hotkey('ctrl', 'c')
    time.sleep(0.5)
    p.press('win')
    time.sleep(0.5)
    p.hotkey('ctrl', 'v')
    time.sleep(0.5)
    p.press('enter')
    p.moveTo(int(str2), int(str3))
    time.sleep(0.5)
    p.click()
if a == 2:
    p.moveTo(343, 237)
    time.sleep(0.5)
    p.doubleClick()
    time.sleep(0.5)
    p.hotkey('ctrl', 'c')
    time.sleep(0.5)
    p.press('win')
    time.sleep(0.5)
    p.hotkey('ctrl', 'v')
    time.sleep(0.5)
    p.press('enter')
    p.moveTo(int(str2), int(str3))
    time.sleep(0.5)
    p.click()
if a == 3:
    p.moveTo(556, 237)
    time.sleep(0.5)
    p.doubleClick()
    time.sleep(0.5)
    p.hotkey('ctrl', 'c')
    time.sleep(0.5)
    p.press('win')
    time.sleep(0.5)
    p.hotkey('ctrl', 'v')
    time.sleep(0.5)
    p.press('enter')
    p.moveTo(int(str2), int(str3))
    time.sleep(0.5)
    p.click()
f.close()