import pyautogui as p
import time
import keyboard as k
p.press('win')
time.sleep(0.5)
k.write('123.txt')
time.sleep(1)
p.press('enter')
time.sleep(0.5)
p.moveTo(559, 288)
time.sleep(0.5)
p.doubleClick()
time.sleep(0.5)
p.hotkey('ctrl', 'c')
time.sleep(0.5)
p.press('win')
time.sleep(0.5)
p.hotkey('ctrl', 'v')
time.sleep(0.5)
p.press('enter')
time.sleep(0.5)
p.hotkey('alt', 'tab')
time.sleep(0.5)
p.moveTo(572, 319)
time.sleep(0.5)
p.doubleClick()
time.sleep(0.5)
p.hotkey('ctrl', 'c')
time.sleep(0.5)
p.hotkey('alt', 'tab')
time.sleep(0.5)
p.hotkey('ctrl', 'v')
time.sleep(0.5)
p.press('enter')

#Point(x=559, y=288)
#Point(x=572, y=319)