f = open('123.txt', 'r', encoding="utf-8")
str1 = f.readline()
str2 = f.readline()
str3 = f.readline()
str4 = f.readline()
print('Имя:', str1)
print('Суперспособность:', str2)
print('Возраст(лет):', str3)
print('Слабость:', str4)
f.close()
s1 = input('Изменить имя?')
s2 = input('Изменить суперспособность?')
s3 = input('Изменить возраст(лет)?')
s4 = input('Изменить слабость?')

if s1 == 'да' or s1 == 'Да' or s1 == 'ДА':
    f1 = open('123.txt', 'w', encoding="utf-8")
    q = input('Введите новое имя.')
    q1 = f1.write(q+'\n'+str2+str3+str4)
    f1.close()
if s2 == 'да' or s2 == 'Да' or s2 == 'ДА':
    f2 = open('123.txt', 'w', encoding="utf-8")
    w = input('Введите новую суперспособность.')
    w2 = f2.write(str1+w+'\n'+str3+str4)
    f2.close()
if s3 == 'да' or s3 == 'Да' or s3 == 'ДА':
    f3 = open('123.txt', 'w', encoding="utf-8")
    e = input('Введите новый возраст(лет).')
    e3 = f3.write(str1+str2+e+'\n'+str4)
    f3.close()
if s4 == 'да' or s4 == 'Да' or s4 == 'ДА':
    f4 = open('123.txt', 'w', encoding="utf-8")
    r = input('Введите новую слабость.')
    r4 = f4.write(str1+str2+str3+r)
    f4.close()