import turtle as t
f = open('123.txt', 'r', encoding="utf-8")
x1 = f.readline().strip()
y1 = f.readline().strip()
x2 = f.readline().strip()
y2 = f.readline().strip()
x3 = f.readline().strip()
y3 = f.readline().strip()
x4 = f.readline().strip()
y4 = f.readline().strip()
t.goto(int(x1), int(y1))
t.goto(int(x2), int(y2))
t.goto(int(x3), int(y3))
t.goto(int(x4), int(y4))
f.close()